# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - adyentestapp

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
                                                                                                                                                                                                                                                                                                                                                                                                                            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A43E744834F462888667EF2CDE7DDD6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9B37A7551F764D78A70507D9A38EE3E3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'adyentestapp'
          slot-name: 'Production'
          package: .
